/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.ventas.frame;

import ar.com.ventas.entities.Configuracion;
import ar.com.ventas.main.MainFrame;
import ar.com.ventas.services.ConfiguracionService;
import com.jacob.activeX.ActiveXComponent;
import com.jacob.com.Dispatch;
import com.jacob.com.LibraryLoader;
import com.jacob.com.Variant;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mario
 */
public class ConsultaAfipFrame extends javax.swing.JFrame {

    private final DecimalFormat df = new DecimalFormat("#0");
//    private Integer order_num;
//    private String order_name;
    
    /**
     * Creates new form ConsultaAfipFrame

     */
    public ConsultaAfipFrame() {
        initComponents();
        limpiarCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        consultarBtn = new javax.swing.JButton();
        volverBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ultimaFcATxt = new javax.swing.JTextField();
        ultimaFcBTxt = new javax.swing.JTextField();
        ultimaNcATxt = new javax.swing.JTextField();
        ultimaNcBTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        exceptionTxt = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        numFcATxt = new javax.swing.JTextField();
        numFcBTxt = new javax.swing.JTextField();
        numNcATxt = new javax.swing.JTextField();
        numNcBTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CONSULTA AFIP");

        jLabel1.setText("Ultimo Comprobante Fc. A:");

        jLabel2.setText("Ultimo Comprobante Fc. B:");

        jLabel3.setText("Ultimo Comprobante Nc. A:");

        jLabel4.setText("Ultimo Comprobante Nc. B:");

        consultarBtn.setText("Consultar");
        consultarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarBtnActionPerformed(evt);
            }
        });

        volverBtn.setText("Volver");
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("Exception:");

        ultimaFcATxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ultimaFcATxt.setText("FCA");

        ultimaFcBTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ultimaFcBTxt.setText("FCB");

        ultimaNcATxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ultimaNcATxt.setText("NCA");

        ultimaNcBTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ultimaNcBTxt.setText("NCB");

        exceptionTxt.setColumns(20);
        exceptionTxt.setRows(5);
        jScrollPane1.setViewportView(exceptionTxt);

        jLabel6.setText("AFIP");

        jLabel7.setText("SISTEMA");

        numFcATxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        numFcATxt.setText("FC A");

        numFcBTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        numFcBTxt.setText("FC B");

        numNcATxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        numNcATxt.setText("Nc A");

        numNcBTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        numNcBTxt.setText("Nc B");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(consultarBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volverBtn)
                .addGap(91, 91, 91))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(ultimaFcATxt, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(ultimaFcBTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(ultimaNcBTxt))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(ultimaNcATxt, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(126, 126, 126)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numFcATxt)
                            .addComponent(numFcBTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(numNcATxt)
                            .addComponent(numNcBTxt))))
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(141, 141, 141))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ultimaFcATxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numFcATxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ultimaFcBTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numFcBTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ultimaNcATxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numNcATxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ultimaNcBTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numNcBTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(volverBtn)
                    .addComponent(consultarBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void consultarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarBtnActionPerformed
        consultar();
    }//GEN-LAST:event_consultarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaAfipFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaAfipFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaAfipFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaAfipFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaAfipFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton consultarBtn;
    private javax.swing.JTextArea exceptionTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numFcATxt;
    private javax.swing.JTextField numFcBTxt;
    private javax.swing.JTextField numNcATxt;
    private javax.swing.JTextField numNcBTxt;
    private javax.swing.JTextField ultimaFcATxt;
    private javax.swing.JTextField ultimaFcBTxt;
    private javax.swing.JTextField ultimaNcATxt;
    private javax.swing.JTextField ultimaNcBTxt;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        ultimaFcATxt.setText("");
        ultimaFcBTxt.setText("");
        ultimaNcATxt.setText("");
        ultimaNcBTxt.setText("");
        exceptionTxt.setText("");
        numFcATxt.setText("");
        numFcBTxt.setText("");
        numNcATxt.setText("");
        numNcBTxt.setText("");
    }

    private void consultar() {
        Configuracion co = null;
        try {
            co = new ConfiguracionService().getFacturas(1L);
        } catch (Exception ex) {
            Logger.getLogger(ConsultaAfipFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (co != null) {
            numFcATxt.setText(df.format(co.getNumeroFacturaA()));
            numFcBTxt.setText(df.format(co.getNumeroFacturaB()));
            numNcATxt.setText(df.format(co.getNumeroNotaCreditoA()));
            numNcBTxt.setText(df.format(co.getNumeroNotaCreditoB()));
        }
        try {
            LibraryLoader.loadJacobLibrary();
            /* Crear objeto WSAA: Web Service de Autenticación y Autorización */
            ActiveXComponent wsaa = new ActiveXComponent("WSAA");
            System.out.println(Dispatch.get(wsaa, "InstallDir").toString()
                    + " "
                    + Dispatch.get(wsaa, "Version").toString()
            );
            /* Solicitar Ticket de Acceso a AFIP (cambiar URL producción) */
            String wsdl = "https://wsaa.afip.gov.ar/ws/services/LoginCms";
            //https://servicios1.afip.gov.ar/wsfev1/service.asmx
            //String userdir = System.getProperty("user.dir");
            String userdir = "c:/certifaym";
            ///AliasVentas_fbd285a15e3f318.crt
            ///certificado_jose_wsaa.crt
            Dispatch.call(wsaa, "Autenticar",
                    new Variant("wsfe"),
                    new Variant(userdir + "/aym2020_4232d12f5f615fc0.crt"),
                    new Variant(userdir + "/clave_privada_20124127581_202010294251.key"),
                    /*
                    new Variant(userdir + "/nuevo_2018_52c1402efa235ce.crt"),
                    new Variant(userdir + "/clave_privada_20124127581_201811014935.key"),
                     */
                    new Variant(wsdl));
            String excepcion = Dispatch.get(wsaa, "Excepcion").toString();
            //System.out.println("Excepcion: " + excepcion);
            String token = Dispatch.get(wsaa, "Token").toString();
            String sign = Dispatch.get(wsaa, "Sign").toString();
            //System.out.println("Token: " + token + "Sign: " + sign);

            /* Instanciar WSFEv1: WebService de Factura Electrónica version 1 */
            ActiveXComponent wsfev1 = new ActiveXComponent("WSFEv1");

            /* Establecer parametros de uso: */
            Dispatch.put(wsfev1, "Cuit", new Variant("20124127581"));
            Dispatch.put(wsfev1, "Token", new Variant(token));
            Dispatch.put(wsfev1, "Sign", new Variant(sign));

            /* Conectar al websrvice (cambiar URL para producción) */
            String cache = "";
            wsdl = "https://servicios1.afip.gov.ar/wsfev1/service.asmx?WSDL";
            //https://servicios1.afip.gov.ar/wsfev1/service.asmx?WSDL
            Dispatch.call(wsfev1, "Conectar",
                    new Variant(cache),
                    new Variant(wsdl)
            );
//            Dispatch.call(wsfev1, "LoginCMS",
//                    new Variant(wsaa)
//            );
            /* Consultar último comprobante autorizado en AFIP */
            String tipo_cbte = "1";
            tipo_cbte = "1"; //Factura A
//                letraFacturaPapel = "A";
//            } else {
//                tipo_cbte = "6"; //Factura B
//                letraFacturaPapel = "B";
//            }
//            tipoComprob = tipo_cbte;
            String pto_vta = "5"; // Sucursal declarada WS
//            sucursalFacturaPapel = "0005";
            Variant ult = Dispatch.call(wsfev1, "CompUltimoAutorizado",
                    new Variant(tipo_cbte),
                    new Variant(pto_vta));
            //System.out.println("Ultimo comprobante: " + ult.toString());
            ultimaFcATxt.setText(ult.toString());
            excepcion = Dispatch.get(wsfev1, "Excepcion").toString();
            exceptionTxt.setText(excepcion);
            //
            tipo_cbte = "6"; //Factura B
            pto_vta = "5"; // Sucursal declarada WS
            ult = Dispatch.call(wsfev1, "CompUltimoAutorizado",
                    new Variant(tipo_cbte),
                    new Variant(pto_vta));
            ultimaFcBTxt.setText(ult.toString());
            excepcion += Dispatch.get(wsfev1, "Excepcion").toString();
            exceptionTxt.setText(excepcion);
            //
            tipo_cbte = "3"; //Nc A
            pto_vta = "5"; // Sucursal declarada WS
            ult = Dispatch.call(wsfev1, "CompUltimoAutorizado",
                    new Variant(tipo_cbte),
                    new Variant(pto_vta));
            ultimaNcATxt.setText(ult.toString());
            excepcion += Dispatch.get(wsfev1, "Excepcion").toString();
            exceptionTxt.setText(excepcion);
            //
            tipo_cbte = "8"; //Nc B
            pto_vta = "5"; // Sucursal declarada WS
            ult = Dispatch.call(wsfev1, "CompUltimoAutorizado",
                    new Variant(tipo_cbte),
                    new Variant(pto_vta));
            ultimaNcBTxt.setText(ult.toString());
            excepcion += Dispatch.get(wsfev1, "Excepcion").toString();
            exceptionTxt.setText(excepcion);
            //
            JOptionPane.showMessageDialog(this, "Proceso completado");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
