/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ar.com.ventas.frame;

import ar.com.ventas.entities.Cliente;
import ar.com.ventas.entities.FcReserved;
import ar.com.ventas.entities.RenglonFcReserved;
import ar.com.ventas.services.ClienteService;
import ar.com.ventas.services.FcReservedService;
import ar.com.ventas.services.RenglonFcReservedService;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mario
 */
public class TestReserved extends javax.swing.JFrame {

    /**
     * Creates new form TestReserved
     */
    public TestReserved() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grabarBtn = new javax.swing.JButton();
        leerBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        grabarBtn.setText("Grabar");
        grabarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grabarBtnActionPerformed(evt);
            }
        });

        leerBtn.setText("Leer");
        leerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(leerBtn)
                    .addComponent(grabarBtn))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(grabarBtn)
                .addGap(31, 31, 31)
                .addComponent(leerBtn)
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void grabarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grabarBtnActionPerformed
        FcReserved fcr = new FcReserved();
        Cliente cli = null;
        try {
            cli = new ClienteService().getClienteByCodigo("4664");
        } catch (Exception ex) {
            Logger.getLogger(TestReserved.class.getName()).log(Level.SEVERE, null, ex);
        }
        fcr.setCliente(cli);
        fcr.setDescuentoGlobal(0.00);
        fcr.setExento(0.00);
        fcr.setFecha(new Date());
        fcr.setGravado(980.00);
        fcr.setGravadoCigarrillos(350.21);
        fcr.setImpuesto(185.90);
        fcr.setIva(1024.12);
        fcr.setNoGravado(0.00);
        fcr.setTotal(1457.92);
        try {
            fcr = new FcReservedService().saveFcReserved(fcr);
        } catch (Exception ex) {
            Logger.getLogger(TestReserved.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (int i = 0; i < 3; i++) {
            RenglonFcReserved rfcr = new RenglonFcReserved();
            rfcr.setCantidad(5F + i);
            rfcr.setDescripcion("Renglon = "+ String.valueOf(i));
            rfcr.setFacturaReservada(fcr);
            rfcr.setDescuento(0.00);
            rfcr.setExento(0.00);
            rfcr.setGravado(200.18 * (i + 2));
            rfcr.setItemNro(i + 1);
            rfcr.setSugerido(1.41 * (i + 1.5));
            try {
                new RenglonFcReservedService().saveRenglonFcReserved(rfcr);
            } catch (Exception ex) {
                Logger.getLogger(TestReserved.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        JOptionPane.showMessageDialog(this, "Completado");
    }//GEN-LAST:event_grabarBtnActionPerformed

    private void leerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerBtnActionPerformed
        List<FcReserved> reservadas = null;
        try {
            reservadas = new FcReservedService().getAllFcReserved();
        } catch (Exception ex) {
            Logger.getLogger(TestReserved.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (reservadas != null && !reservadas.isEmpty()) {
            for (FcReserved fc: reservadas) {
                System.out.println(fc.getCliente().getRazonSocial());
                System.out.println(fc.getTotal());
                List<RenglonFcReserved> renglones = null;
                try {
                    renglones = new RenglonFcReservedService().getRenglonesDeReserved(fc);
                } catch (Exception ex) {
                    Logger.getLogger(TestReserved.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (renglones != null && !renglones.isEmpty()) {
                    for (RenglonFcReserved rng:renglones) {
                        System.out.println(rng.getCantidad());
                        System.out.println(rng.getItemNro());
                        System.out.println(rng.getGravado());
                        System.out.println("");
                    }
                }
            }
        }
        
    }//GEN-LAST:event_leerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestReserved.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestReserved.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestReserved.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestReserved.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestReserved().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton grabarBtn;
    private javax.swing.JButton leerBtn;
    // End of variables declaration//GEN-END:variables
}
